version: '3.5'

services:

  node:
    deploy:
       replicas: ${NODE_NUM}
    command: nice -n${NICENESS} golemsp run
    build: .
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
#      - /root/.local/share/ya-provider/
#      - /root/.local/share/yagna/
    devices:
      - /dev/kvm:/dev/kvm
    env_file:
      - .env
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.golem-clean.schedule: "@daily"
      ofelia.job-exec.golem-clean.command: "find /root/.local/share/ya-provider/exe-unit/cache/ -mtime +7 -type f -exec rm {} +"
