version: '3.5'

services:

  node:
    container_name: ${COMPOSE_PROJECT_NAME}_node
    image: aabrioux/golem-node:latest
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data-node/ya-provider/:/root/.local/share/ya-provider/
      - ./data-node/yagna/:/root/.local/share/yagna/
    devices:
      - /dev/kvm:/dev/kvm
